# mutagent-diagnostics configuration
# Generated by: pnpx @mutagent/diagnostics init
# Generated at: {{GENERATED_AT}}
# Skill version: {{SKILL_VERSION}}
#
# Full field documentation: .claude/skills/mutagent-diagnostics/references/config.md

# ── Source ───────────────────────────────────────────────────────────────────
source:
  platform: "{{SOURCE_PLATFORM}}"        # langfuse | otel | local-jsonl | claude-code | codex
  config:
    # Langfuse
    # host: "https://cloud.langfuse.com"  # or self-hosted URL
    # Keys: set LANGFUSE_SECRET_KEY + LANGFUSE_PUBLIC_KEY in .mutagentrc

    # OTel
    # endpoint: "http://localhost:4318"
    # Key: set OTEL_EXPORTER_OTLP_HEADERS in .mutagentrc

    # Local JSONL
    # file: "traces.jsonl"

    # Claude Code — auto-detected from ~/.claude/projects/
    # Codex — auto-detected from ~/.codex/sessions/

# ── Target ───────────────────────────────────────────────────────────────────
target:
  platform: "{{TARGET_PLATFORM}}"        # local-claude | local-codex | local-cursor | local-opencode | local-mastra | local-cloud-agent-sdk | cloud-rest
  config: {}                             # platform-specific config (see references/target-platforms/)

# ── Filters ──────────────────────────────────────────────────────────────────
filters:
  time_window:
    from: "7daysAgo"                     # ISO datetime or relative ("7daysAgo", "1h")
    to: "now"
  agent_id: null                         # null = all agents
  has_error: null                        # null = all; true = errors only; false = no errors
  has_feedback: null                     # null = all; true = has feedback
  score_below: null                      # null = no filter; number = threshold (auto-scaled)
  session_id: null                       # null = all sessions
  limit: 100                             # max traces to analyze

# ── ASK Tool ─────────────────────────────────────────────────────────────────
ask_tool:
  runtime: "{{ASK_RUNTIME}}"            # claude-code | chat-multi-choice
  config: {}

# ── Default Audience (W13-D) ─────────────────────────────────────────────────
# Audience used for the rendered report when no explicit --audience flag is passed.
#   client   — client-stripped report (internal nodes NODE-STRIPPED). DEFAULT.
#   internal — full report (Methodology + Trajectory + internal banners).
# A fresh init writes "client" so a published/client install produces the
# client-stripped report by default; internal is opt-in.
# NOTE: self-diagnosis reports are ALWAYS internal regardless of this (PR-022).
default_audience: "client"

# ── Schedule ─────────────────────────────────────────────────────────────────
schedule:
  mode: "on-demand"                      # v0.1: on-demand only; "scheduled" = post-v0.1
  # interval_hours: 168                  # ignored in on-demand mode

# ── Self-Diagnostics [INTERNAL] ──────────────────────────────────────────────
self_diagnostics:
  enabled: false                         # default OFF — requires explicit opt-in
  cadence:
    mode: "on-demand"
    interval_hours: 168
  source_override: null
